// This file was autogenerated by superstartup/source/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
// goog.addDependency('../../../../lib/app.js', ['ssn.core'], ['ssn.user']);
// goog.addDependency('../../../../lib/models/user.model.js', ['ssn.user'], []);
