// This file was autogenerated by superstartup/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../../../lib/app.js', ['ssn.core'], ['ssn.mock.user', 'ssn.user']);
goog.addDependency('../../../../../../lib/mocks/userMock.js', ['ssn.mock.user'], []);
goog.addDependency('../../../../../../lib/models/user.model.js', ['ssn.user'], []);
